import type { Metadata } from 'next';
import { Ballet as FontSans } from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from './ApolloWrapper';
import { cn } from 'lib/utils';
import { PreloadQuery } from './ApolloClient';
import { GET_POSTS_QUERY } from 'api/querries/posts.querries';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <body
          className={cn('bg-background min-h-screen font-sans antialiased')}
        >
          <PreloadQuery
            query={GET_POSTS_QUERY}
            variables={{ options: { paginate: { page: 1, limit: 5 } } }}
          >
            {children}
          </PreloadQuery>
        </body>
      </ApolloWrapper>
    </html>
  );
}
